# Site settings
title: Ravens Wing
email: ki@ravenswing.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ravenswing-io.github.io" # the base hostname & protocol for your site
twitter_username: ravenswing_io
github_username:  ravenswing-io

# Build settings
# markdown: kramdown
markdown: redcarpet

# from http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
redcarpet:
  extensions: ["tables"]
